name: Build LSO
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lowlevel-studios/setup-theos@main
      - name: Build Tweak
        run: make package
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LSOBypass
          path: packages/*.deb
