#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import <substrate.h>

// --- ĐỊNH NGHĨA MENU DUNG X V2 ---
@interface EwwMenu : UIView
+(void)setTitle:(NSString *)title;
+(void)addSwitch:(NSString *)title :(void(^)(BOOL value))block;
@end

@implementation EwwMenu
+(void)setTitle:(NSString *)title {}
+(void)addSwitch:(NSString *)title :(void(^)(BOOL value))block {}
@end

// --- LOGIC GAME ---
struct {
    BOOL BypassMic;
} _G;

bool (*old_IsMuted)(void *instance);
bool new_IsMuted(void *instance) {
    if (_G.BypassMic) return false; 
    return old_IsMuted(instance);
}

static __attribute__((constructor)) void init() {
    [EwwMenu setTitle:@"DUNG X V2"];
    [EwwMenu addSwitch:@"Bypass Mic" :^(BOOL value) {
        _G.BypassMic = value;
    }];
}
