name: Build LSO
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Theos
        run: |
          sudo git clone --recursive https://github.com/theos/theos.git /opt/theos
          sudo chown -R $(id -u):$(id -g) /opt/theos
          echo "THEOS=/opt/theos" >> $GITHUB_ENV
          echo "/opt/theos/bin" >> $
      - name: Build Tweak
        run: |
          cd HackLangSoi
          make package
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LSOBypass
          path: HackLangSoi/packages/*.deb
